### ISSUE TITLE
Logfile Example

### ISSUE THREAD

**Issue by weiweikong** [andybarry/simflight#1]
Hi,
 would it be possible to share some `.mat` files for testing the project, because that
the setup of the code need `logfile_name` linking to the specific log data.

```
realtime_path = '/home/abarry/realtime/';
logfile_path = '/home/abarry/rlg/logs/2015-09-17-field-test/odroid-gps2/';

logfile_name = 'lcmlog_2015_09_17_04.mat';
```

Thanks

**Comment by andybarry** [comment]
Sure, what are you trying to look at?  The system identification, simulation, or something else?

**Comment by weiweikong** [comment]
I would prefer to know more detail about the Trajectory Libraries, TVLQR feedback control and Online Planning, which based on this simulation environment. Or maybe some more introduction about the code would be better.

Also, I just finished watching your defense video, but there are still some details not mentioned during the talk. Is your thesis file online available?

Merry Christmas! ~

**Comment by andybarry** [comment]
Merry Christmas!  I uploaded some log files and added links to the README.  Take a look and let me know if it's what you were looking for.  I'll upload the final pdf for my thesis in the next few days.

**Comment by weiweikong** [comment]
- Try to run `do_pem.m`file
  Matlab reply `Undefined function or variable 'loadDeltawing'`. Does this function require `drake`?
  Shoud I put the `lcmlog-*` and `lcmlog-*.jlp` into `scripts/logs'?
- Try to load the log file using `LoadAllogs.m`
  It required `trajlib_path = 'traj-archive/oct8-from-data-obstacle-ready.mat';`, does this relate to the `*.jlp` file?
- Image Sequence
  Are there stereo pairs in these log? I would like to know the visual perception detail from the matching point to generate obstacle map and onboard state Estimation.

Would it be possible to give a short step-by-step introduction to load and test the log files for visual perception, trajectory planning and onboard control?

**Comment by andybarry** [comment]
Sorry, some of the .m files were mixed in with my other repo "flight."  I moved them into this repo and changed a few things so that you can do almost everything without that repo.

I updated the README with some examples.  Look at the beginning of `do_pem.m` and see if loading the logs works.

There are not images posted online yet -- I'll open another issue for that.

Let me know if the examples work and/or what else I should add.

**Comment by weiweikong** [comment]
Thanks for your update. There are some further errors.
- For `do_pem.m`
  There is a `realtime_path` which also has sub path`scripts/logs`. 
  Is this the same folder as `logfile_path`? But `logfile_path` should only contain `.mat` files which downloaded from `odroid-gps2-2015-09-17-field-test.zip`.
- For `BuildTrajectoryLibrary`
  - There was a warning 
  
  ```
   LCM: Disabling IPV6 support
   LCM: TTL set to zero, traffic will not leave localhost.
  ```
  
  Is this a warning from Drake?
  - some java path
  
  ```
  Error initializing LCM types.  If you want to use the HUD visualizer, you need to run:
  javaaddpath('/home/abarry/realtime/LCM/LCMtypes.jar');
  javaaddpath('/home/abarry/pronto-distro/build/share/java/lcmtypes_mav-lcmtypes.jar');
  javaaddpath('/home/abarry/pronto-distro/build/share/java/lcmtypes_mav_estimator.jar');
  ```
- For Stereo Vision
  I already got the stereo videos, but did not find the related `.m` files which detect the obstacles ant generate path during the flight. As you mentioned, this supporiting vision algorithms towards to another issue which did not include in this one?

**Comment by andybarry** [comment]
`realtime_path` is the path to my other repo: https://github.com/andybarry/flight but I added some code which should mean that you don't need it.  The `Error initializing LCM types.  If you want to use the HUD visualizer, you need to run` error is telling you that you don't have that path, so it's disabling some functionality that you probably don't need (using a HUD visualizer in addition to the normal visualizer).

```
LCM: Disabling IPV6 support
LCM: TTL set to zero, traffic will not leave localhost.
```

are super-standard LCM warnings that you'll always see when using something with LCM in Matlab.  Don't worry about those at all.

The stereo vision part isn't impemented in this repo (or in MATLAB).  You'll find that in C++ over in my flight repo.  Look here: 

https://github.com/andybarry/flight/blob/master/sensors/stereo/pushbroom-stereo.hpp and https://github.com/andybarry/flight/blob/master/sensors/stereo/pushbroom-stereo-main.hpp

**Comment by andybarry** [comment]
Since you asked before, my thesis is now online: http://abarry.org/Barry16.pdf

**Comment by andybarry** [comment]
Datafiles are now online.
